name: Build and publish

on:
  push:
    branches:
      - master
  workflow_dispatch:
        branches:
            - 'master'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out repository code
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.APP_PRIVATE_KEY }}


    - name : Conventional Changelog Action
      id : changelog
      uses: TriPSs/conventional-changelog-action@v3
      with:
          github-token: ${{ secrets.APP_PRIVATE_KEY }} 
          git-user-name: ${{github.actor}} 
          skip-on-empty: false
        
    - name: Create Release # This action will create the actual release
      if: ${{ steps.changelog.outputs.skipped == 'false' }}  
      uses: actions/create-release@v1 
      env:
        GITHUB_TOKEN: ${{ secrets.APP_PRIVATE_KEY }}  
      with:
        tag_name: ${{ steps.changelog.outputs.tag }}
        release_name: ${{ steps.changelog.outputs.tag }}
        body: ${{ steps.changelog.outputs.clean_changelog }}
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Build with Maven
      run: mvn clean install

    # - name: Publish to GitHub Packages Apache Maven
    #   run: mvn deploy
    #   env:
    #     GITHUB_TOKEN: ${{ github.token }} # GITHUB_TOKEN is the default env for the password
    - name: Logging in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{vars.ACR_SERVER}}
        username: ${{vars.ACR_USERNAME}}
        password: ${{secrets.ACR_PASSWORD}}
   
    - name: Build and push images
      run: |
          export VERSION=${{steps.changelog.outputs.tag}}
          export CONTAINER_REGISTRY=${{vars.ACR_SERVER}}
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

   
